#################################################################
#                                                               #
# Copyright (c) 2019-2020 YottaDB LLC and/or its subsidiaries.  #
# All rights reserved.                                          #
#                                                               #
#       This source code contains the intellectual property     #
#       of its copyright holder(s), and is made available       #
#       under a license.  If you do not know the terms of       #
#       the license, please stop and do not read further.       #
#                                                               #
#################################################################

stages:
  - build
  - docs

before_script:
  # libssl-dev for cargo-deadlinks
  - apt-get update -qq && apt-get install -y -qq git curl libclang-common-6.0-dev clang libsdl2-dev libsdl2-gfx-dev libsdl2-doc libsdl2-ttf-dev libssl-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source /opt/yottadb/current/ydb_env_set
  - source $HOME/.cargo/env

rust-compat:
  stage: build
  image: yottadb/yottadb-base:latest-master
  script:
    - rustup toolchain install 1.34.0
    - rustup default 1.34.0
    - cargo build --verbose

rust-latest:
  stage: build
  image: yottadb/yottadb-base:latest-master
  script:
    # Copy commit gpg key verify script to build directory and execute
    - wget https://gitlab.com/YottaDB/DB/YDB/-/raw/master/ci/commit_gpgkey_verify.sh
    - chmod +x commit_gpgkey_verify.sh
    - ./commit_gpgkey_verify.sh
    - CONTINUOUS_INTEGRATION=1 tests/copyright.sh
    - cargo fmt -- --check
    - cargo clippy -- --deny clippy::all
    - cargo build --verbose
    - cargo test --verbose
    - cargo run --example xyzInitRust
    # NOTE: exits with success if and only if `xyzTransRust` times out
    # This prevents false negatives due to the compile failing and false positives due to the timeout.
    - timeout 5s cargo run --example xyzTransRust && false || [ $? = 124 ]
    - cargo run --example xyzVerifyRust

rust-no-vendor:
  stage: build
  image: yottadb/yottadb-base:latest-master
  cache:
    paths:
      - ~/.cargo/bin/bindgen
  script:
    - cargo install --debug bindgen
    - cargo check --no-default-features

rust-nightly:
  stage: build
  image: yottadb/yottadb-base:latest-master
  script:
    - rustup toolchain install nightly
    - rustup default nightly
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

pages:
  image: yottadb/yottadb-base:latest-master
  stage: docs
  dependencies:
    - rust-latest
  cache:
    paths:
      - ~/.cargo/bin/cargo-deadlinks
  script:
    - cargo doc --no-deps
    - cargo install --debug cargo-deadlinks
    - cargo deadlinks
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=yottadb">' > public/index.html
  artifacts:
    paths:
      - public
    when: always
