[package]
name = "yottadb"
version = "0.1.1"
authors = ["Charles Hathaway <charles@yottadb.com>", "Joshua Nelson <joshua@yottadb.com>"]
edition = "2018"

description = "Rust wrappers for the NoSQL database YottaDB"
license = "AGPL-3.0-only"
repository = "https://gitlab.com/YottaDB/Lang/YDBRust"
homepage = "https://yottadb.com/"
readme = "README.md"

[dependencies]

[build-dependencies]
bindgen = "0.42.2"
pkg-config = "0.3.14"

[dev-dependencies]
threadpool = "1.7.1"
rand = "0.6.5"
num_cpus = "1.10.0"

[dev-dependencies.sdl2]
version = "0.32.2"
features = ["gfx", "ttf"]
