#!/bin/sh

#################################################################
#                                                               #
# Copyright (c) 2020 YottaDB LLC and/or its subsidiaries.       #
# All rights reserved.                                          #
#                                                               #
#       This source code contains the intellectual property     #
#       of its copyright holder(s), and is made available       #
#       under a license.  If you do not know the terms of       #
#       the license, please stop and do not read further.       #
#                                                               #
#################################################################

set -e

# Check copyrights first
tests/copyright.sh

# Check formatting
cargo fmt -- --check

# Do some lint checks using clippy
cargo clippy -- --deny clippy::all

# Previously we had a call to "cargo test" here. But it is a heavyweight task to run all tests for every commit
# Since the pipeline does run "cargo test", that is considered good enough and the "cargo test" call here has been removed.

